### PR TITLE
Able to receive a object in query

### PR DESCRIPTION
**Pull request by rpaggi**
This change able the user to send a query like this example:
var data = {name:"test", age:25};
var id = 1;
c.query("UPDATE table SET ? WHERE id = ?", [data, id], function(err, rows)...

In resume, it get the data var and parse to SQL friendly format
{name:"test", age:25} = name = 'test', age = 25

### CODE REVIEW

**Comment by repsac-by** [comment]
Your code do not applies escaping keys and values

**Comment by rpaggi** [comment]
>Your code do not applies escaping keys and values

I changed, now are ready

**Comment by repsac-by** [comment]
The keys need to wrap it with backtick.
To get around the object keys is better using Object.keys(v). Therefore, you do not need to check hasOwnProperty(), which you have not, but should be.

**Comment by rpaggi** [comment]
How i can use Object.keys(v) in this case?

**Comment by mscdex** [comment]
@rpaggi You'd iterate over the array returned by `Object.keys(v)` and use the array values as the column names (surrounded by backticks).

**Comment by rpaggi** [comment]
This way is correct:

**Comment by mscdex** [comment]
I think a regular for-loop (non-for-in) would work better (and perform better IIRC).

**Comment by rpaggi** [comment]
I think now is better:

**Comment by mscdex** [comment]
Yeah that looks better, a couple of minor nits though:
- Style issues (need spacing after `if` and between `){`)
- We should coerce `v[keys[i]]` to a string by concatenating with an empty string: `'' + v[keys[i]]`

After those changes feel free to update the PR

**Comment by rpaggi** [comment]
@mscdex Thanks for the help, i sent a new commit.

**Comment by rpaggi** [comment]
What is wrong with build?

**Comment by mscdex** [comment]
I wouldn't worry about it, there's a workaround missing in the AppVeyor config.

**Comment by knoxcard** [comment]
@rpaggi - (My Two Cents) - You know what would be better?  Make node-mariasql a driver for Sequelize (https://www.npmjs.com/package/sequelize), Sequelize has all this syntax and more, it's superrr simple!
Leave node-mariasql as a backend and use Sequelize ORM for the front end.  Right now I am using sequelize and hundreds of thousands are as well but we are all using the MySQL driver, they need the mariadb driver and this library looks like the proper fit.

**Comment by knoxcard** [comment]
@rpaggi - tell me how much cleaner this is...https://medium.com/@sarahdherr/sequelizes-update-method-example-included-39dfed6821d

Bada Bing!  It's practically English.

**Pull request closed without merging**
