### PR TITLE
fix corrupted big querys (> 70K + much concurrency)

### PR DESCRIPTION
**Pull request by not-implemented**
We got some random strange syntax errors from MySQL server with bigger querys. The error was only reproducable when there were a lot of concurrent operations. When issuing just this one big query, it always worked.

TCP-Dump showed that the ~100 KiB query was transmitted fine until ~79 KiB ... and then garbage followed, so the server error was correct.

After looking at the code, we noticed that `mysql_real_query_start()` is given the pointer `cur_query` ... but the underlying string was initialized before **on local stack** with `Nan::Utf8String query_s(info[0]);` ...

The documentation of `mysql_real_query_start()` is not clear about this, but is _seems_ (I didn't check this) that it does not copy the query again, but just uses the pointer internally for subsequent `mysql_real_query_cont()` calls. So it is not guaranteed that the query is still in memory then (depending on v8 garbage collection). As I don't know the internals of v8 garbage collection, I didn't even try to implement a stable test case for that :-)

So we tried to implement a reference to `cur_query` as `cur_query_ref` class member (instead of local `query_s`) and free it after `mysql_real_query_start/cont()` is complete (and in class destructor). So we avoided to create an additional copy of the query every time.

With this patch the problem was not reproducable anymore.

But - please check if there are still conditions where this patch will produce memory leaks.

### CODE REVIEW

**Comment by mscdex** [comment]
I think it'd probably be better to just `cur_query = strdup(qry);` in `query()` instead of adding another state variable.

**Comment by not-implemented** [comment]
Would also be possible, of course. We wanted to avoid an additional copy of the entire query (we use it for batch inserts for example which may be 1 MB or more per query). But I didn't benchmark the overhead of an additional `strdup` copy - maybe it is not as much as I think :-)

**Comment by mscdex** [comment]
The `new Nan::Utf8String()` is [already doing an allocation on large strings followed by a copy](https://github.com/nodejs/nan/blob/baa8436ed26cb2f7b2494a12d19befc38d19d612/nan.h#L898-L905), so you would have already noticed a performance difference if there was one.

I suppose if we wanted to avoid copying the string at all, we could replace the `cur_query` variable entirely with a `Persistent<String>` variable, assign `info[0]` to it in `query()`, and clear it on query finish/error/etc.

**Comment by not-implemented** [comment]
Yes, but if I understood correctly, this happens too with `Nan::Utf8String query_s(info[0]);` ... so it is at least no difference there. I don't know, if there is a better solution - as I know, the internal string representation in v8 is "UCS-2" or "UTF-16" - so **one** conversation has to be done anyway, or am I wrong?

I have rewritten the patch now (nearly as supposed) to eliminate one of the two `cur_query` variables:

- `Local<Value>` is now passed to the `query()` function instead of `const char*`
- `new`/`delete` is now consistently done inside the (non-static) class functions
- ... and a small benefit: we save one `strlen()` as we already know the length from the Utf8String :-)

Any further suggestions?

**Comment by mscdex** [comment]
I believe this will still need to be made a Persistent, otherwise I think the GC is able to collect the query string value when the parent scope goes away.

**Comment by not-implemented** [comment]
I'm not sure, which one you want to make persistent. The (converted) Utf8String is the one we have to held until `mysql_real_query_cont()` completes. As you showed me, `Nan::Utf8String` allocates it's own memory ... and frees it on destruction - independent from v8 garbage collection (so my original estimation was wrong - reproducing the error does not depend on v8 garbage collection, but on `malloc()` usage).

So the `Local<Value>` in `query()` should be fine, I think. Because after the conversion, we don't need the original string anymore.

If there is a possibility to use the original string directly, the whole thing can be rewritten, of course.

_Off Topic:_ Theoretically `Nan::Utf8String` can even be transparently re-implemented by using the original pointer (+ increment/decrement reference count for v8) instead of copying the string - for example if the string is currently already ASCII (which seems sometimes to be the case - but I'm not familiar with the v8 internals) - this would still be possible with the patch.

**Comment by not-implemented** [comment]
By the way: Is the Travis build error ("Segmentation fault (core dumped)") in node 0.10 an old one, or was it introduced by this patch?

**Comment by devzer01** [comment]
@not-implemented i think the segfault is because of a race condition in one of my earlier patches for a memory-leak. this issue is now fixed in #133 waiting for @mscdex Brian to merge the fix.

**Comment by not-implemented** [comment]
@devzer01 ah, ok tnx :-)

**Comment by mscdex** [comment]
Hey guys, I haven't forgotten these PRs, honest. I've just been very swamped with day job stuff, sorry.

**Comment by not-implemented** [comment]
No problem :-) Do you have any further suggestions for this patch?

**Comment by not-implemented** [comment]
@mscdex ping :-)

**Comment by mscdex** [comment]
@not-implemented I've pushed @devzer01's changes now and [CI ran into an error](https://travis-ci.org/mscdex/node-mariasql/jobs/111053592) while re-testing your PR with master. I re-tested the new changes pushed to master to make sure it wasn't that causing problems and so far I've re-tested those changes several times with no failure, so I suspect it is this PR.

**Comment by not-implemented** [comment]
@mscdex I've rebased the "fix-big-querys" branch of this pull-request onto the current master. Now Travis does not complain anymore :-)

**Comment by mscdex** [comment]
@not-implemented Ok looks good now after several passes on Travis.

Landed in fdda5d733a501b59bd8ae4543b7680e6427c4f27. Thanks!

**Comment by not-implemented** [comment]
@mscdex Cool, Thanks.

**Pull request closed without merging**
